### ISSUE TITLE
Leaking methods onto the jQuery object could cause conflicts

### ISSUE THREAD

**Issue by tentonaxe** [jchavannes/jquery-timer#15]
When you call `$.timer()`, `this` is `$`, therefore you're attaching functions to `$` directly when you do `this.toggle = function () {...}`. Here's a fiddle demonstrating the issue: http://jsfiddle.net/shnom7c9/

All of the functions you define on `this` are being set on `$`.

**Comment by jchavannes** [comment]
@tentonaxe Thanks for the info.  I believe https://github.com/jchavannes/jquery-timer/pull/12 will resolve that.

**Comment by tentonaxe** [comment]
Yes, that would take care of it. Sorry i missed the other issue. :)
