### ISSUE TITLE
$ npm install @types/jquery.timer --save-dev

### ISSUE THREAD

**Issue by zhangyu528** [jchavannes/jquery-timer#19]
ERROR in /Users/zhangyu27/Documents/git.oschina.net/DuoBaoWeb/src/app/app.component.ts (19,24): Property 'timer' does not exist on type 'JQueryStatic<HTMLElement>'.

ERROR in /Users/zhangyu27/Documents/git.oschina.net/DuoBaoWeb/src/app/app.component.ts (21,11): Cannot find name 'JQueryTimer'.

Why?

**Comment by zhangyu528** [comment]
Anybody konws the reason? Please....

**Comment by jchavannes** [comment]
@zhangyu528 that is an issue with the NPM package - https://www.npmjs.com/package/@types/jquery.timer

I do not maintain that package, which looks to be part of this github library - https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jquery.timer

I would recommend contacting them.

**Comment by zhangyu528** [comment]
Thank you so much.
I have contacted them.
