### ISSUE TITLE
license

### ISSUE THREAD

**Issue by ghost** [jchavannes/jquery-timer#7]
Can you please provide/include the license under which this software can be used? Is it under MIT license? If so can you please explicitly state that and include the license in the zip file?

Thank you,

AJ

**Comment by aviau** [comment]
@jchavannes It would be appreciated that you tagged this repository. I am packaging jquery-timer for Debian and we use version numbers to keep track with upstream.

**Comment by jchavannes** [comment]
License file has been added.  Sorry for not getting it in earlier.

And @aviau, it's probably not relevant anymore, but I've created a tag - https://github.com/jchavannes/jquery-timer/releases/tag/v1.0

**Comment by MatthewVance** [comment]
Thanks for updating this. No worries on the delay. I appreciate it when code like this is released with an open license.
